export const SET_DANH_SACH_SAN_PHAM = 'SET_DANH_SACH_SAN_PHAM'

export const SET_SAN_PHAM_IPHONE15 = 'SET_SAN_PHAM_IPHONE15'

export const SET_SAN_PHAM_IPHONE14 = 'SET_SAN_PHAM_IPHONE14'
export const SET_SAN_PHAM_IPHONE13 = 'SET_SAN_PHAM_IPHONE13'
export const SET_SAN_PHAM_IPHONE11 = 'SET_SAN_PHAM_IPHONE12'
export const SET_SAN_PHAM_IPHONE12 = 'SET_SAN_PHAM_IPHONE11'
export const SET_SAN_PHAM_IPHONESE = 'SET_SAN_PHAM_IPHONESE'


export const SET_SAN_PHAM_ALL = 'SET_SAN_PHAM_ALL'
export const SET_CHI_TIET_SAN_PHAM = 'SET_CHI_TIET_SAN_PHAM'
